### ISSUE TITLE
Failure on missing data

### ISSUE THREAD

**Issue by rgieseke** [greenelab/manubot#75]
I'm getting 

```
Error parsing references: Could not parse RefDate
Error running filter pandoc-citeproc:
Filter returned error status 1
Traceback (most recent call last):
  File "/home/robert/openclimatedata/global-emissions/venv/bin/manubot", line 11, in <module>
    sys.exit(main())
  File "/home/robert/openclimatedata/global-emissions/venv/lib/python3.6/site-packages/manubot/command.py", line 141, in main
    function(args)
  File "/home/robert/openclimatedata/global-emissions/venv/lib/python3.6/site-packages/manubot/cite/cite_command.py", line 98, in cli_cite
    format=args.format,
  File "/home/robert/openclimatedata/global-emissions/venv/lib/python3.6/site-packages/manubot/cite/cite_command.py", line 60, in call_pandoc
    process.check_returncode()
  File "/usr/lib/python3.6/subprocess.py", line 369, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['pandoc', '--filter', 'pandoc-citeproc', '--output', '-', '--to', 'markdown_strict', '--wrap', 'none']' returned non-zero exit status 83.
```

for 

`manubot cite --render --format markdown doi:10.5194/gmd-11-369-2018-supplement`

Only running cite gives:

```json
[
  {
    "publisher": "Copernicus GmbH",
    "DOI": "10.5194/gmd-11-369-2018-supplement",
    "source": "Crossref",
    "issued": {
      "date-parts": [
        []
      ]
    },
    "URL": "https://doi.org/gfddtf",
    "id": "GbPj2EzP",
    "type": "entry"
  }
]
```
Maybe it could fail more gracefully for such (obviously lacking) data.

**Comment by dhimmel** [comment]
This is another instance of https://github.com/greenelab/manubot/issues/66.

I opened a PR with the CSL Schema to fix this upstream in https://github.com/citation-style-language/schema/pull/158, i.e. not to allow empty `date-parts` arrays.

We've also got a manubot PR open to fix this in https://github.com/greenelab/manubot/pull/65. In the meantime, you could add the above to `manual-references.json` and manually set the proper `issued/date-parts`.

**Comment by rgieseke** [comment]
Thanks and sorry for the dupe!
