### ISSUE TITLE
Error getting citation data for doi:10.6084/m9.figshare.5346577

### ISSUE THREAD

**Issue by ostrokach** [greenelab/manubot#89]
I am getting an "The resource you are looking for doesn't exist" error trying to fetch one of the citations present in `manubot-rootstock`:

```python-traceback
>>> from manubot.cite.util import citation_to_citeproc
>>> citation_to_citeproc("doi:10.6084/m9.figshare.5346577")
ERROR:root:Error fetching metadata for doi:10.6084/m9.figshare.5346577.
Invalid response from https://data.datacite.org/10.6084%2Fm9.figshare.5346577:
The resource you are looking for doesn't exist.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/anaconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/util.py", line 225, in citation_to_citeproc
    citeproc = citeproc_retriever(identifier)
  File "/home/username/anaconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/doi.py", line 46, in get_doi_citeproc
    raise error
  File "/home/username/anaconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/doi.py", line 42, in get_doi_citeproc
    citeproc = response.json()
  File "/home/username/anaconda3/envs/manubot/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/username/anaconda3/envs/manubot/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/username/anaconda3/envs/manubot/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/username/anaconda3/envs/manubot/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
----

Linux Mint
Anaconda Python 3.6.
Manubot 0.2.2.

**Comment by agitter** [comment]
> I'd suggest upgrading to the latest manubot-rootstock which will contain several citation enhancements.

@ostrokach there are upgrade instructions here: https://github.com/greenelab/manubot-rootstock/blob/master/SETUP.md#merging-upstream-manubot-rootstock-changes

Ping @dhimmel or me if you run into any problems upgrading.  To resolve merge conflicts, you may have to remove `02.delete-me.md` and other files again if they were deleted in your repo before.

**Comment by ostrokach** [comment]
OK, great. Thanks!
